### ISSUE TITLE
[Bug]: Deforum - Interpolate Pics is not working and gives an error message 

### ISSUE THREAD

**Issue by michholl1965** [Tok/sd-forge-deforum#11]
### What happened and why was it ungood?

**Using Interpolate Pics sd-forge-deforum  gives an error message:**
" folder_name = clean_folder_name(Path(pic_list[0].orig_name).stem)
AttributeError: 'NamedString' object has no attribute 'orig_name'"

The same procedure is working fine in the original extension for AUTOMATIC1111's webui..

How to reproduce:

1. Select tab Deforum

![image](https://github.com/user-attachments/assets/d524864f-5a88-4003-96c7-622bd02d27b0)

2. Select tab Output

![image](https://github.com/user-attachments/assets/b7510365-6bac-4d06-a09e-2c737c087e13)

3. Perform Interpocate Pics according (1)-(4):
![image](https://github.com/user-attachments/assets/c3ee2096-e737-4bcf-acd8-4269626c3afd)

4. Result: Error Message:

![image](https://github.com/user-attachments/assets/a9c8a6af-7534-4d72-ba96-5a5af96e37c1)

5. System Message as txt:
"got a request to frame interpolate a set of 2 images.
Traceback (most recent call last):
File "C:\Apps\webui_forge_cu121_torch231\system\python\lib\site-packages\gradio\queueing.py", line 536, in process_events
response = await route_utils.call_process_api(
File "C:\Apps\webui_forge_cu121_torch231\system\python\lib\site-packages\gradio\route_utils.py", line 285, in call_process_api
output = await app.get_blocks().process_api(
File "C:\Apps\webui_forge_cu121_torch231\system\python\lib\site-packages\gradio\blocks.py", line 1923, in process_api
result = await self.call_function(
File "C:\Apps\webui_forge_cu121_torch231\system\python\lib\site-packages\gradio\blocks.py", line 1508, in call_function
prediction = await anyio.to_thread.run_sync( # type: ignore
File "C:\Apps\webui_forge_cu121_torch231\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
return await get_asynclib().run_sync_in_worker_thread(
File "C:\Apps\webui_forge_cu121_torch231\system\python\lib\site-packages\anyio_backends_asyncio.py", line 877, in run_sync_in_worker_thread
return await future
File "C:\Apps\webui_forge_cu121_torch231\system\python\lib\site-packages\anyio_backends_asyncio.py", line 807, in run
result = context.run(func, *args)
File "C:\Apps\webui_forge_cu121_torch231\system\python\lib\site-packages\gradio\utils.py", line 818, in wrapper
response = f(*args, **kwargs)
File "C:\Apps\webui_forge_cu121_torch231\webui\extensions\sd-forge-deforum\scripts\deforum_helpers\gradio_funcs.py", line 132, in upload_pics_to_interpolate
process_interp_pics_upload_logic(pic_list, engine, x_am, sl_enabled, sl_am, keep_imgs, f_location, f_crf, f_preset, fps, f_models_path, resolution, add_audio, audio_track)
File "C:\Apps\webui_forge_cu121_torch231\webui\extensions\sd-forge-deforum\scripts\deforum_helpers\frame_interpolation.py", line 220, in process_interp_pics_upload_logic
folder_name = clean_folder_name(Path(pic_list[0].orig_name).stem)
AttributeError: 'NamedString' object has no attribute 'orig_name' "

**Comment by Tok** [comment]
Thanks for reporting the issue. Here's the fix: https://github.com/Tok/sd-forge-deforum/commit/7329856872a57bc2b9665cff046fbb6d8e538697
