### ISSUE TITLE
[Bug]: openCV error -215 while using Parseq

### ISSUE THREAD

**Issue by furibrz** [Tok/sd-forge-deforum#12]
### What happened and why was it ungood?

Not sure whether to post this here or to Parseq repo. While trying to generate a video using default parseq document:

Info: Sampler: 'DPM++ 2M SDE' Scheduler: 'Karras'
### Warning: Frames have been removed. Original count: 19, New count: 8
Info: Calculated pseudo cadence: 30.25
Info: Precalculating 4 seeds with behaviour 'iter'.
Info: Created 4 key frames with 120 tweens. Key frame index distribution: 'KEYFRAMES_ONLY'.

Animation frame: 1/121
Seed: -1
Prompt: A lone (black cat:0.89117) (white duck:0.10883) at midday, centered, realistic, photorealism, crisp, natural colors, fine textures, highly detailed, volumetric lighting, studio photography
Neg Prompt: (black cat:0.10883) (white duck:0.89117) watermark, logo, text, signature, copyright, writing, letters, low quality, artefacts, cropped, bad art, poorly drawn, lowres, simple, pixelated, grain, noise, blurry, cartoon, computer game, video game, painting, drawing, sketch, disfigured, deformed, ugly
Not using an init image (doing pure txt2img)
╭─────┬───┬─────────┬───────┬───────┬─────────┬────┬────┬────┬────┬────┬────┬──────────╮
│Steps│CFG│Dist. CFG│Denoise│Subseed│Subs. str│Tr X│Tr Y│Tr Z│Ro X│Ro Y│Ro Z│Asp. Ratio│
├─────┼───┼─────────┼───────┼───────┼─────────┼────┼────┼────┼────┼────┼────┼──────────┤
│  8  │2.5│   2.5   │   0   │  -1   │    0    │ 0  │ 0  │1.1 │ 0  │ 0  │ 0  │    1     │
╰─────┴───┴─────────┴───────┴───────┴─────────┴────┴────┴────┴────┴────┴────┴──────────╯
[Unload] Trying to free 2457.60 MB for cuda:0 with 1 models keep loaded ... Current free memory is 14643.73 MB ... Done.
100%|######################################################################################################################################| 8/8 [00:03<00:00,  2.30it/s]
Tweens progress:   0%|                                                                                                                            | 0/40 [00:00<?, ?it/s]
*START OF TRACEBACK*
Traceback (most recent call last):
  File "C:\AI\forge\webui\extensions\sd-forge-deforum\scripts\deforum_helpers\run_deforum.py", line 124, in run_deforum
    render_animation(args, anim_args, video_args, parseq_args, loop_args, controlnet_args, freeu_args, kohya_hrfix_args, root)
  File "C:\AI\forge\webui\extensions\sd-forge-deforum\scripts\deforum_helpers\render.py", line 64, in render_animation
    experimental_core.render_animation(args, anim_args, video_args, parseq_args, loop_args, controlnet_args, freeu_args, kohya_hrfix_args, root)
  File "C:\AI\forge\webui\extensions\sd-forge-deforum\scripts\deforum_helpers\rendering\experimental_core.py", line 26, in render_animation
    run_render_animation(data, diffusion_frames)
  File "C:\AI\forge\webui\extensions\sd-forge-deforum\scripts\deforum_helpers\rendering\experimental_core.py", line 34, in run_render_animation
    _pre_process_diffusion_frame_and_emit_tweens(data, diffusion_frame)
  File "C:\AI\forge\webui\extensions\sd-forge-deforum\scripts\deforum_helpers\rendering\experimental_core.py", line 46, in _pre_process_diffusion_frame_and_emit_tweens
    emit_tweens(data, diffusion_frame)
  File "C:\AI\forge\webui\extensions\sd-forge-deforum\scripts\deforum_helpers\rendering\experimental_core.py", line 67, in emit_tweens
    [tween.emit_frame(frame, grayscale_tube, overlay_mask_tube) for tween in tweens]
  File "C:\AI\forge\webui\extensions\sd-forge-deforum\scripts\deforum_helpers\rendering\experimental_core.py", line 67, in <listcomp>
    [tween.emit_frame(frame, grayscale_tube, overlay_mask_tube) for tween in tweens]
  File "C:\AI\forge\webui\extensions\sd-forge-deforum\scripts\deforum_helpers\rendering\data\frame\tween_frame.py", line 36, in emit_frame
    new_image = image_utils.save_and_return_frame(data, self, new_image)
  File "C:\AI\forge\webui\extensions\sd-forge-deforum\scripts\deforum_helpers\rendering\util\image_utils.py", line 40, in save_and_return_frame
    save_cadence_frame_and_depth_map_if_active(data, frame, image)
  File "C:\AI\forge\webui\extensions\sd-forge-deforum\scripts\deforum_helpers\rendering\util\image_utils.py", line 33, in save_cadence_frame_and_depth_map_if_active
    save_cadence_frame(data, frame.i(), image)
  File "C:\AI\forge\webui\extensions\sd-forge-deforum\scripts\deforum_helpers\rendering\util\image_utils.py", line 29, in save_cadence_frame
    cv2.imwrite(save_path, image)
cv2.error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:798: error: (-215:Assertion failed) !_img.empty() in function 'cv::imwrite'

*END OF TRACEBACK*

User friendly error message:
Error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:798: error: (-215:Assertion failed) !_img.empty() in function 'cv::imwrite'
. Please, check your schedules/ init values.
Tweens progress:   0%|

**Comment by asdrabael** [comment]
Do you get the same error if you use a different scheduler? Also what model? That error indicates that something is causing an error where it's not saving pictures. 2.5 cfg and 2.5 distilled cfg is also something I've never seem someone do. If you're using Flux some schedulers give funky errors.

**Comment by furibrz** [comment]
Hey. I'm using the DreamShaper XL Turbo model, hence the low cfg and steps. i'm using the DPM++ sampler with the Karras scheduler.

**Comment by asdrabael** [comment]
I'm not sure if it works with turbo models. That's a distinction outside of my expertise. Some stuff like controlnet gives similar issues, so that's my best guess until Tok weighs in

**Comment by Tok** [comment]
## ✅ Fixed in PR #18

This issue has been resolved by adding image validation before  calls.

**Changes made:**
- Added validation in `scripts/deforum_helpers/save_images.py` - `dump_frames_cache()`
- Added validation in `scripts/deforum_helpers/render.py` - cadence frame saving

**Fix:**
```python
# Validate image before saving to prevent OpenCV assertion errors
if img is not None and hasattr(img, 'shape') and img.size > 0:
    cv2.imwrite(image_cache['path'], img)
else:
    print(f"Warning: Skipping save for {image_cache['path']} - invalid or empty image")
```

This prevents the OpenCV assertion error when Parseq or other processes generate invalid/empty images.

**Merged in:** https://github.com/Tok/sd-forge-deforum/pull/18

**Comment by Tok** [comment]
Closing as fixed in main branch.
