### ISSUE TITLE
[Bug]: Error: None. Please, check your schedules/ init values. [ google colab ]

### ISSUE THREAD

**Issue by organicmind-pixel** [Tok/sd-forge-deforum#13]
### What happened and why was it ungood?

i got errors when try in google colab today ,, " Loading MiDaS model from dpt_large-midas-2f21e586.pt...
Info: Calculating shake 'INVESTIGATION' at intensity 1 with speed 1.

*START OF TRACEBACK*
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/stable-diffusion-webui-forge/extensions/sd-forge-deforum/scripts/deforum_helpers/run_deforum.py", line 124, in run_deforum
    render_animation(args, anim_args, video_args, parseq_args, loop_args, controlnet_args, freeu_args, kohya_hrfix_args, root)
  File "/content/gdrive/MyDrive/stable-diffusion-webui-forge/extensions/sd-forge-deforum/scripts/deforum_helpers/render.py", line 64, in render_animation
    experimental_core.render_animation(args, anim_args, video_args, parseq_args, loop_args, controlnet_args, freeu_args, kohya_hrfix_args, root)
  File "/content/gdrive/MyDrive/stable-diffusion-webui-forge/extensions/sd-forge-deforum/scripts/deforum_helpers/rendering/experimental_core.py", line 21, in render_animation
    data = RenderData.create(args, parseq_args, anim_args, video_args, loop_args, controlnet_args, freeu_args,
  File "/content/gdrive/MyDrive/stable-diffusion-webui-forge/extensions/sd-forge-deforum/scripts/deforum_helpers/rendering/data/render_data.py", line 83, in create
    shaker = Shaker.create(incomplete_init)
  File "/content/gdrive/MyDrive/stable-diffusion-webui-forge/extensions/sd-forge-deforum/scripts/deforum_helpers/rendering/data/shakify/shaker.py", line 54, in create
    name, source_fps, shake_data = SHAKE_LIST[Shaker.shake_name_to_key(shake_name)]
KeyError: None
*END OF TRACEBACK*

User friendly error message:
Error: None. Please, check your schedules/ init values."

**Comment by Ka7IO** [comment]
I had the same error, under Distribution Tab => Shakify ==> set Shake Name to "None"

**Comment by Tok** [comment]
## ✅ Fixed in PR #18

This Camera Shakify error has been resolved with enhanced validation.

**Changes made:**
- Enhanced validation in `scripts/deforum_helpers/rendering/data/shakify/shaker.py`

**Fix:**
```python
# Enhanced null/empty/invalid checks
return aa.shake_name and aa.shake_name != 'None' and aa.shake_name != '' and aa.shake_name is not None

# Validate shake_key exists before accessing SHAKE_LIST
if shake_key is None or shake_key not in SHAKE_LIST:
    log_utils.warn(f"Camera shake name '{shake_name}' not found! Defaulting to 'None'.")
    return Shaker('None', 1.0, 1.0, {}, False)
```

This prevents KeyError crashes on Google Colab and other environments when invalid shake patterns are provided.

**Merged in:** https://github.com/Tok/sd-forge-deforum/pull/18

**Comment by Tok** [comment]
Closing as fixed in main branch.
