### ISSUE TITLE
[Bug]: Error executing callback ui_tabs

### ISSUE THREAD

**Issue by MajorGruberth** [Tok/sd-forge-deforum#14]
### What happened and why was it ungood?

Deforum tab is not shown in the UI.
console error:
Error executing callback ui_tabs_callback for /content/stable-diffusion-webui-forge/extensions/sd-webui-deforum/scripts/deforum.py
    Traceback (most recent call last):
      File "/content/stable-diffusion-webui-forge/modules/script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "/content/stable-diffusion-webui-forge/extensions/sd-webui-deforum/scripts/deforum_helpers/ui_right.py", line 38, in on_ui_tabs
        with gr.Row(elem_id='deforum_progress_row').style(equal_height=False, variant='compact'):
    AttributeError: 'Row' object has no attribute 'style'

Any ideas how to fix it?

**Comment by ssaqibalitipu** [comment]
still getting the issue
2025-02-06 00:08:49,690 - ControlNet - INFO - ControlNet UI callback registered.
*** Error executing callback ui_tabs_callback for K:\pinokio\api\stable-diffusion-webui-forge.git\app\extensions\sd-forge-deforum\scripts\deforum.py
    Traceback (most recent call last):
      File "K:\pinokio\api\stable-diffusion-webui-forge.git\app\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "K:\pinokio\api\stable-diffusion-webui-forge.git\app\extensions\sd-forge-deforum\scripts\deforum_helpers\ui_right.py", line 38, in on_ui_tabs
        with gr.Row(elem_id='deforum_progress_row').style(equal_height=False, variant='compact'):
    AttributeError: 'Row' object has no attribute 'style'

**Comment by Tok** [comment]
## ✅ Already Fixed

This UI tabs callback error has already been resolved in the current main branch.

The error was related to deprecated Gradio `.style()` calls which have been removed from the codebase.

**Status:** No changes needed in PR #18 - already working in main branch.

**Related PR:** https://github.com/Tok/sd-forge-deforum/pull/18

**Comment by Tok** [comment]
Closing as already fixed in main branch.
