### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by dron28** [Tok/sd-forge-deforum#7]
*** Error loading script: deforum.py
    Traceback (most recent call last):
      File "C:\forge2\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\forge2\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\forge2\webui\extensions\sd-forge-deforum\scripts\deforum.py", line 22, in <module>
        from scripts.deforum_extend_paths import deforum_sys_extend
    ModuleNotFoundError: No module named 'scripts.deforum_extend_paths'

---
*** Error loading script: deforum_api.py
    Traceback (most recent call last):
      File "C:\forge2\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\forge2\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\forge2\webui\extensions\sd-forge-deforum\scripts\deforum_api.py", line 29, in <module>
        from scripts.deforum_api_models import Batch, DeforumJobErrorType, DeforumJobStatusCategory, DeforumJobPhase, DeforumJobStatus
    ModuleNotFoundError: No module named 'scripts.deforum_api_models'

**Comment by Tok** [comment]
Hi 

thanks for reporting the error.
I can't really reproduce it and I'm not sure why it happens.

It looks like your installation might miss two files "deforum_api_models.py" and "deforum_extend_paths.py"
which should have been downloaded during installation: https://github.com/Tok/sd-forge-deforum/tree/main/scripts

I would recommend to try uninstall the extension, including deleting the "extensions/sd-forge-deforum" directory and then reinstall it again directly in Forge. (I just tested the latest version on "main" as working with the Forge one-click installer).

also try updating your deforum-settings.txt with this if you have an outdated version:
https://raw.githubusercontent.com/Tok/sd-forge-deforum/main/scripts/default_settings.txt
